// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCVNcRbJOultuI3cDKtjztfkwrN0U8ZJP4',
    appId: '1:995749538257:web:4460c2c320f54e7b0f18f0',
    messagingSenderId: '995749538257',
    projectId: 'surfing-app-46dc2',
    authDomain: 'surfing-app-46dc2.firebaseapp.com',
    databaseURL: "https://surfing-app-46dc2-default-rtdb.europe-west1.firebasedatabase.app",
    storageBucket: 'surfing-app-46dc2.appspot.com',
    measurementId: 'G-J2WETF7V3P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBebHVr2sCRN8C_st7ziQ0nrpxAOEGCU2s',
    appId: '1:995749538257:android:f1e3e2120e4b18ea0f18f0',
    databaseURL: "https://surfing-app-46dc2-default-rtdb.europe-west1.firebasedatabase.app",
    messagingSenderId: '995749538257',
    projectId: 'surfing-app-46dc2',
    storageBucket: 'surfing-app-46dc2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDjIBulRBIQ2sUvcu7u1xVBPGb7Bps98qg',
    appId: '1:995749538257:ios:3ce7fb8eb33373c30f18f0',
    messagingSenderId: '995749538257',
    projectId: 'surfing-app-46dc2',
    databaseURL: "https://surfing-app-46dc2-default-rtdb.europe-west1.firebasedatabase.app",
    storageBucket: 'surfing-app-46dc2.appspot.com',
    iosBundleId: 'com.example.surfApp2',
  );
}
